### PR TITLE
Multiprocessing atom

### PR DESCRIPTION
**Pull request by maxcountryman**

### CODE REVIEW

**Comment by maxcountryman** [comment]
Should fix #3 as well.

cc @wiliamsouza

**Comment by wiliamsouza** [comment]
Great! From where the hack come from? I'm curious about it.

**Comment by maxcountryman** [comment]
@wiliamsouza https://docs.python.org/2/library/multiprocessing.html#customized-managers

I think ideally in the future that would be configurable at runtime, but for now maybe that ad hoc manager instantiation and startup is all right.

**Comment by wiliamsouza** [comment]
Do you think make sense create a threaded version of the tests? https://github.com/maxcountryman/atomos/compare/master...wiliamsouza:bug/atomic_reference#diff-bd41b9374c6239ee4b68bdd5098b5ef1R85

**Comment by maxcountryman** [comment]
I added a [test here](https://github.com/maxcountryman/atomos/commit/281c1d6a884e609a227ede47ea38286d6fb0810f).

**Comment by wiliamsouza** [comment]
LGTM :+1:

**Comment by maxcountryman** [comment]
Seems like this is failing to build on Python 3.2 but works on 2.7, 3.3, and 3.4.

**Comment by maxcountryman** [comment]
@wiliamsouza do you think it's fine to drop Python 3.2 support?

**Comment by wiliamsouza** [comment]
No time to debug this, I agree.

**Pull request merged**
